language: node_js
node_js:
- '0.8'
- '0.10'
deploy:
  api_key:
    - secure: "KYmYojCPvKhqUnMv0d4kOXTFYHqM+p9iT9M9Wa2Fo3ylwfLhoby0Tf5HaEyRHYmFcUm8dJ/yvOuSSLlvPWT0Dsulh0G7qwuLv/XwDX+IY2uLdXROacyfI7CmreNapnVKa6usdRUn7RJHLK8bP4A3vgnM9hIVupdi4t4Q+962HdmN35SKqVgmMYXqqxRLmLazE/NwUMbdvWYHc6gfAJ6OiyhQbVj3xhi0Z4oloP6T+ATugLqFz5AKje8ka9n1tzq+cU9759Xw6KMpUGXxKt+GAbg4WEO9mVqL2cVkIjl0qxw46ZFkKA726lt46hDP+EsQ5xmCniHI/a32nme8Rn1/Om2AilBlM4yoNvTrxzGJjM9oB9QNIV9+P/UARJAo27WaIbq8iv9a2VWpIZqU6q0t53HDO3zPXaLHWxFVLTMQ6uU2U3DQQwQ2MZ2Hz8eeCnOubzv/8NZwHSuSsQ2CQkeq4mUhXXBoJOOX4SVr2C9Ye9cLPAS0whlyLuzzAs/zhMxbDsbo4ZLlP9puz+4064O86x7SR1ckUwd9JjoF8Lu23rxVTTC00ovMZZTh7ndXro9L+cDOplqji89nq4MV+U41DA+Sn4TQ3ggwvVURKFABYrTgrj5v7dOuHk5A3hTc78hIbh4RrTCdMMqiNw47H6CzTgr1oWBB+eQOhbr+BItbpCI="
